include ../lunar/go.mk

# ------------------------------------------------------------------------------
# Global configuraiton.
# ------------------------------------------------------------------------------
REPO      = fsx
LIB_DIR   = src
CMD_DIR   = cmd

LIBS      = github.com/xiejw/${REPO}/${LIB_DIR}/...

# CMD family is for cmd folder.
#
#   - CMDP go module path for all cmds.
#   - CMDS cmd names.
#   - CMDB output binary files. The make rule is generated by objs template.
#
CMDP      = github.com/xiejw/${REPO}/${CMD_DIR}/...
CMDS      = $(patsubst ${CMD_DIR}/%,%,$(wildcard ${CMD_DIR}/*))
CMDB      = $(patsubst ${CMD_DIR}/%,${BUILD_DIR}/%,$(wildcard ${CMD_DIR}/*))

# ------------------------------------------------------------------------------
# Actions.
# ------------------------------------------------------------------------------
#
.PHONY: compile ${LIBS}

compile: ${BUILD_DIR} ${LIBS} ${CMDB}

${LIBS}:
	${GO} $@

fmt:
	${FM} ${LIBS}
	${FM} ${CMDP}

test:
	${TS} ${LIBS}

clean:
	${CL} rm -rf ${BUILD_DIR} && go mod tidy

# ------------------------------------------------------------------------------
# Binaries.
#
# Generate CMDB from CMDS. See objs template for conventions.
# ------------------------------------------------------------------------------

$(foreach cmd_name,$(CMDS),$(eval $(call objs,$(cmd_name),$(BUILD_DIR))))

